spring:
  application:
    name: Sistema-Biblioteca

  datasource:
    url: url_banco
    username: username
    password: ${DB_PASSWORD:senha}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
      jwt:
        secret: ${JWT_SECRET}
        expiration-time: 3600000